sudo: false
language: node_js


node_js:
  - "10"

cache:
  directories:
  - node_modules
  
install:
  - npm install
    
script:
  - node index.js

deploy:
    provider: gae
    skip_cleanup: true
    keyfile: client-secret.json
    project: instbotrpa
    default: true
 

notifications:
  email:
    recipients:
      - sebasmtech@gmail.com
    on_success: never
    on_failure: always

