sudo: false
language: node_js

before_install:
  - gcloud auth activate-service-account --key-file client-secret.json
  
install:
  
  - gcloud config set project instbotrpa
    
  - npm install

script:
  - node index.js

  - gcloud -q app deploy app.yaml --promote

 

notifications:
  email:
    recipients:
      - sebasmtech@gmail.com
    on_success: never
    on_failure: always

