language: node_js
dist: trusty
sudo: false
git:
  depth: 1
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"
install:
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable
  
script:
  - node index.js
 
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - sebasmtech@gmail.com
    on_success: never
    on_failure: always
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: client-secret.json
    project: instbotrpa
    default: true
   